---
http_interactions:
- request:
    method: post
    uri: "<salesforce_instance_url>/services/data/v37.0/sobjects/Lead"
    body:
      encoding: UTF-8
      string: '{"FirstName":"Rigoberto","LastName":"Kris","Company":"unknown to Accounts","Country":"United
        States","Email":"f@f.com","LeadSource":"Instructor Verification","Newsletter__c":false,"Newsletter_Opt_In__c":false,"OS_Accounts_ID__c":5,"accounts_uuid_c__c":"5d2835a1-49ed-472b-88e6-98ee0d9e6abb","Application_Source__c":"Tutor
        Signup","Role__c":"instructor","FV_Status__c":"pending_faculty","FV_Final__c":true,"Needs_CS_Review__c":false,"BRI_Marketing__c":false,"Title_1_school__c":false}'
    headers:
      User-Agent:
      - Faraday v1.0.1
      Content-Type:
      - application/json
      Authorization:
      - OAuth <salesforce_access_token>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 201
      message: Created
    headers:
      Date:
      - Mon, 24 May 2021 19:17:14 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=pbel17zEEeuJ_2k9a-m5LA; domain=.salesforce.com; path=/; expires=Tue,
        24-May-2022 19:17:14 GMT; Max-Age=31536000
      - BrowserId_sec=pbel17zEEeuJ_2k9a-m5LA; domain=.salesforce.com; path=/; expires=Tue,
        24-May-2022 19:17:14 GMT; Max-Age=31536000; secure; SameSite=None
      Sforce-Limit-Info:
      - api-usage=1065/5000000
      Location:
      - "/services/data/v37.0/sobjects/Lead/00Q7h000006zd36EAA"
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"id":"00Q7h000006zd36EAA","success":true,"errors":[]}'
    http_version: 
  recorded_at: Mon, 24 May 2021 19:17:15 GMT
- request:
    method: get
    uri: "<salesforce_instance_url>/services/data/v37.0/query?q=SELECT%20Id,%20Name,%20FirstName,%20LastName,%20Salutation,%20Subject__c,%20Company,%20City,%20State,%20StateCode,%20Country,%20Phone,%20Website,%20Status,%20Email,%20LeadSource,%20Newsletter__c,%20Newsletter_Opt_In__c,%20Adoption_Status__c,%20Number_of_Students__c,%20OS_Accounts_ID__c,%20accounts_uuid_c__c,%20Application_Source__c,%20Role__c,%20other_role_name__c,%20who_chooses_books__c,%20FV_Status__c,%20FV_Final__c,%20Needs_CS_Review__c,%20BRI_Marketing__c,%20Title_1_school__c,%20SheerID_School_Name__c,%20Account_ID__c,%20School__c%20FROM%20Lead%20WHERE%20(accounts_uuid_c__c%20=%20%275d2835a1-49ed-472b-88e6-98ee0d9e6abb%27)%20LIMIT%201"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Faraday v1.0.1
      Authorization:
      - OAuth <salesforce_access_token>
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
      Accept:
      - "*/*"
  response:
    status:
      code: 200
      message: OK
    headers:
      Date:
      - Mon, 24 May 2021 19:17:15 GMT
      Strict-Transport-Security:
      - max-age=31536000; includeSubDomains
      X-Robots-Tag:
      - none
      Cache-Control:
      - no-cache,must-revalidate,max-age=0,no-store,private
      Set-Cookie:
      - BrowserId=po59JrzEEeuqo5eba5FwtA; domain=.salesforce.com; path=/; expires=Tue,
        24-May-2022 19:17:15 GMT; Max-Age=31536000
      - BrowserId_sec=po59JrzEEeuqo5eba5FwtA; domain=.salesforce.com; path=/; expires=Tue,
        24-May-2022 19:17:15 GMT; Max-Age=31536000; secure; SameSite=None
      Sforce-Limit-Info:
      - api-usage=1066/5000000
      Content-Type:
      - application/json;charset=UTF-8
      Vary:
      - Accept-Encoding
      Transfer-Encoding:
      - chunked
    body:
      encoding: ASCII-8BIT
      string: '{"totalSize":1,"done":true,"records":[{"attributes":{"type":"Lead","url":"/services/data/v37.0/sobjects/Lead/00Q7h000006zd36EAA"},"Id":"00Q7h000006zd36EAA","Name":"Rigoberto
        Kris","FirstName":"Rigoberto","LastName":"Kris","Salutation":null,"Subject__c":null,"Company":"unknown
        to Accounts","City":null,"State":null,"StateCode":null,"Country":"United States","Phone":null,"Website":null,"Status":"Convert","Email":"f@f.com","LeadSource":"Instructor
        Verification","Newsletter__c":false,"Newsletter_Opt_In__c":false,"Adoption_Status__c":null,"Number_of_Students__c":null,"OS_Accounts_ID__c":"5","accounts_uuid_c__c":"5d2835a1-49ed-472b-88e6-98ee0d9e6abb","Application_Source__c":"Tutor
        Signup","Role__c":"Instructor","other_role_name__c":null,"who_chooses_books__c":null,"FV_Status__c":"pending_faculty","FV_Final__c":true,"Needs_CS_Review__c":false,"BRI_Marketing__c":false,"Title_1_school__c":false,"SheerID_School_Name__c":null,"Account_ID__c":null,"School__c":null}]}'
    http_version: 
  recorded_at: Mon, 24 May 2021 19:17:15 GMT
recorded_with: VCR 3.0.3
